{"name": "test_check_firmware_version_exists", "status": "broken", "statusDetails": {"message": "NameError: name 'os' is not defined", "trace": "self = <src.tests.test_4_firmware_information.TestFirmwareInformation object at 0x00000277B738FB50>\nfirmware_information_page = <src.pages.FirmwareInformationPage.FirmwareInformationPage object at 0x00000277B7354FD0>\n\n    def test_check_firmware_version_exists(self, firmware_information_page):\n>       result = firmware_information_page.get_firmware_version_exists()\n\nsrc\\tests\\test_4_firmware_information.py:24: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <src.pages.FirmwareInformationPage.FirmwareInformationPage object at 0x00000277B7354FD0>\n\n    def get_firmware_version_exists(self)->bool:\n        from dotenv import load_dotenv\n        load_dotenv(\"Settings.env\")\n>       firmware_version = os.getenv('FIRMWARE_VERSION')\nE       NameError: name 'os' is not defined\n\nsrc\\pages\\FirmwareInformationPage.py:46: NameError"}, "start": 1744610670646, "stop": 1744610670648, "uuid": "4a476247-be15-420d-92f8-019588ab17d5", "historyId": "126f1cbe303285e3886d8c5c5e91293e", "testCaseId": "126f1cbe303285e3886d8c5c5e91293e", "fullName": "src.tests.test_4_firmware_information.TestFirmwareInformation#test_check_firmware_version_exists", "labels": [{"name": "parentSuite", "value": "src.tests"}, {"name": "suite", "value": "test_4_firmware_information"}, {"name": "subSuite", "value": "TestFirmwareInformation"}, {"name": "host", "value": "Perry"}, {"name": "thread", "value": "12432-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "src.tests.test_4_firmware_information"}]}