{"uuid": "79ca3544-eafc-4056-9638-91dab3265cd9", "children": ["f9dc7ce1-e761-43fc-89ad-3093fa40d549", "f7255307-d1ec-462e-a1ab-20f0160681d0", "4caa4d5d-333b-46b2-bd1d-a9efd3e3bcdf", "bc1a37e7-bf49-406e-8e9b-a97f194b28d8"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.\n  (chrome not reachable)\n  (The process started from chrome location C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n\tGetHandleVerifier [0x00007FF75F6CFB05+28789]\n\t(No symbol) [0x00007FF75F6386E0]\n\t(No symbol) [0x00007FF75F4D592A]\n\t(No symbol) [0x00007FF75F5101E4]\n\t(No symbol) [0x00007FF75F50BC59]\n\t(No symbol) [0x00007FF75F55A77C]\n\t(No symbol) [0x00007FF75F559D60]\n\t(No symbol) [0x00007FF75F54F1E3]\n\t(No symbol) [0x00007FF75F51A938]\n\t(No symbol) [0x00007FF75F51BAA1]\n\tGetHandleVerifier [0x00007FF75FA0933D+3410093]\n\tGetHandleVerifier [0x00007FF75FA1E7DD+3497293]\n\tGetHandleVerifier [0x00007FF75FA12A73+3448803]\n\tGetHandleVerifier [0x00007FF75F797BBB+848171]\n\t(No symbol) [0x00007FF75F643C3F]\n\t(No symbol) [0x00007FF75F63F6E4]\n\t(No symbol) [0x00007FF75F63F87D]\n\t(No symbol) [0x00007FF75F62ED49]\n\tBaseThreadInitThunk [0x00007FFAA9A07374+20]\n\tRtlUserThreadStart [0x00007FFAAA6BCC91+33]\n\n", "trace": "  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1125, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 880, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\Projects\\WebUI\\src\\conftest.py\", line 36, in driver\n    driver = webdriver.Chrome(\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 45, in __init__\n    super().__init__(\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 66, in __init__\n    super().__init__(command_executor=executor, options=options)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 212, in __init__\n    self.start_session(capabilities)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 299, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1735871967306, "stop": 1735871990898}], "start": 1735871967306, "stop": 1735871991076}